### ISSUE TITLE
Resovle the function name uniqueness issue

### ISSUE THREAD

**Issue by johnjiabinzhang** [microvm/uPy#1]
`str(graph)` gives a unique yet invalid function name as an identifier in μIR.
Proposed solution:
Take the line number, prepends it with an underscore in front of the plain function name.
e.g:
320_strconcat__Signed
2_f

**Comment by wks** [comment]
Using a sequentially assigned ID is easier and is more resilient to errors.
Actually "linking" is also an interesting topic alongside loading. Linking
is to decide which actual function corresponds to which called function.
You may wish to know more about how linkers (for c) work and why C++ did a
very bad job in binary compatibility.

John Zhang <notifications@github.com>于2015年4月25日星期六写道：

**Comment by johnjiabinzhang** [comment]
That's a good suggestion. I'll change my code when I get to it.
But I think the line number shouldn't be too bad either. There is a
possibility of clashing, however the possibility for both the line numbers
AND the specialised function name to be the same would be very small, I
think.

I've made some nice progress. Now I'm able to dump the string constants,
load them at loading time, and correctly gets the length of the loaded
string constants. :D
